[project]
name = "simple-dbt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.3",
    "dbt-duckdb>=1.9.3",
    "duckdb>=1.3.0",
    "sqlfluff>=3.4.0",
]
